# introduction to scikit learn (sklearn)

This notebook demonstrates some of the most useful functions of the Scikit-Learn library.

What we are going to cover:

0. an end-to-end sklearn workflow
1. getting data ready
2. choose right estimator/algorithm for our problems
3. fit the model/algorithm and use it to make predictions on our data
4. evaluating  a model
5. improve a model
6. save and load trained model
7. putting it all together

In [9]:
what_were_covering = [
    "0. an end-to-end sklearn workflow",
    "1. getting data ready",
    "2. choose right estimator/algorithm for our problems",
    "3. fit the model/algorithm and use it to make predictions on our data",
    "4. evaluating a model",
    "5. improve a model",
    "6. save and load trained model",
    "7. putting it all together"
]

## 0. an end-to-end sklearn workflow

In [10]:
# 1. get the data ready
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("csv/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [11]:
# create X (feature matrix)
X = heart_disease.drop("target", axis=1)

# create y (labels/ label matrix)
y = heart_disease["target"]

In [12]:
import warnings
warnings.filterwarnings("default")

In [13]:
# 2. choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [14]:
# 3. fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
import sklearn
sklearn.show_versions()

/Users/viragvegh/Desktop/sample_project/env/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")



System:
    python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ]
executable: /Users/viragvegh/Desktop/sample_project/env/bin/python
   machine: macOS-12.1-x86_64-i386-64bit

Python dependencies:
          pip: 22.1.2
   setuptools: 62.3.3
      sklearn: 1.0.2
        numpy: 1.22.3
        scipy: 1.7.3
       Cython: None
       pandas: 1.4.2
   matplotlib: 3.5.1
       joblib: 1.1.0
threadpoolctl: 3.1.0

Built with OpenMP: True


In [16]:
clf.fit(X_train, y_train);

In [17]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
133   41    1   1       110   235    0        1      153      0      0.0   
110   64    0   0       180   325    0        1      154      1      0.0   
192   54    1   0       120   188    0        1      113      0      1.4   
166   67    1   0       120   229    0        0      129      1      2.6   
245   48    1   0       124   274    0        0      166      0      0.5   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
51    66    1   0       120   302    0        0      151      0      0.4   
10    54    1   0       140   239    0        1      160      0      1.2   
61    54    1   1       108   309    0        1      156      0      0.0   
229   64    1   2       125   309    0        1      131      1      1.8   
162   41    1   1       120   157    0        1      182      0      0.0   

     slope  ca  thal  
133      2   0     2  
110      2   0     2  
192      1   1     3  
166      1   2     3  
245      1   0     3  
..     ...  ..   ...  
51       1   0     2  
10       2   0     2  
61       2   0     3  
229      1   0     3  
162      2   0     2  

[242 rows x 13 columns]

In [18]:
# 3. make a prediction
y_label = clf.predict(np.array([0, 2, 3, 4]))

/Users/viragvegh/Desktop/sample_project/env/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
y_preds = clf.predict(X_test)
y_preds

In [ ]:
y_test

In [ ]:
X_test

In [ ]:
X_train

In [ ]:
 # 4. evaluate the model on training data and test data
clf.score(X_train, y_train)

In [ ]:
clf.score(X_test, y_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

In [ ]:
confusion_matrix(y_test, y_preds)

In [ ]:
accuracy_score(y_test, y_preds)

In [ ]:
# 5. improve a model
# try different amount of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators..")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test)*100:2f}%")
    print("")

In [ ]:
# 6. save a model and load it
import pickle
#pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))


loaded_model = open('random_forest_model_1.pkl', 'wb')
pickle.dump(clf, loaded_model)
loaded_model.close()

In [ ]:
#loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
#loaded_model.score(X_test, y_test)

loaded_model = open('random_forest_model_1.pkl','rb')
clf = pickle.load(loaded_model)
loaded_model.close()

In [ ]:
what_were_covering

In [ ]:
# standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1. getting our data ready to use

Three main things we have to do:
    1. split the data into features and labels (usually 'X' and 'y')
    2. filling (also called imputing) or disreagrding missing values
    3. converting non-num values to numerical values (also called feature encoding)

In [ ]:
heart_disease.head()

In [ ]:
X = heart_disease.drop("target", axis=1)
X.head()

In [ ]:
y = heart_disease["target"]
y.head()

In [ ]:
# split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

In [ ]:
X.shape[0] * 0.8

In [ ]:
len(heart_disease)

In [ ]:
242 + 61

In [ ]:
import pandas as pd

## 1.1 Make sure it is all numerical

In [ ]:
car_sales = pd.read_csv("csv/car-sales-extended.csv")
car_sales

In [ ]:
len(car_sales)

In [ ]:
car_sales.dtypes

In [ ]:
# split into X/y

X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# split into training and test set

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.2)

In [ ]:
# build machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

In [ ]:
X.head()

In [ ]:
# turn the categories (Make column) into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

In [ ]:
pd.DataFrame(transformed_X)

In [ ]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

In [ ]:
# Let's refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)
model.fit(X_train, y_train)

In [ ]:
model.score(X_test, y_test)

## 1.2 What if there were missing values?
1. fill them with some values (also known as imputation)
2. remove the samples with missing data alltogether

In [ ]:
# import car sales missing data
car_sales_missing = pd.read_csv("csv/car-sales-extended-missing-data.csv")
car_sales_missing.head()

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
# create X and y
X = car_sales_missing.drop("Price", axis = 1)
y = car_sales_missing["Price"]

In [ ]:
# Let's try and convert our data to numbers
# turn categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

In [ ]:
car_sales_missing

#### option 1: Fill missing data with pandas

In [ ]:
# Fill the Make column 
car_sales_missing["Make"].fillna("missing", inplace=True)

# Fill the colour column
car_sales_missing["Colour"].fillna("missing", inplace=True)

# Fill the Odometer (KM) column with mean
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# fill the doors column
car_sales_missing["Doors"].fillna(4, inplace=True)

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
# remove the rows with missing price values
car_sales_missing.dropna(inplace=True)

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
len(car_sales_missing)

In [ ]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [ ]:
# Let's try and convert our data to numbers
# turn categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

### Option 2: fill missing values with scikit-learn

In [ ]:
car_sales_missing = pd.read_csv("csv/car-sales-extended-missing-data.csv")
car_sales_missing.head()

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
# drop the rows with no label
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

In [ ]:
# split into X and y
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [ ]:
X.isna().sum()

In [ ]:
# fill missing values with scikit-learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# fill categorical values w 'missing' & numerical values w mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# define column
cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# create an imputer (something that fills missing data)
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_features),
    ("num_imputer", num_imputer, num_features)
])

# transform the data
filled_X = imputer.fit_transform(X)
filled_X

In [ ]:
car_sales_filled = pd.DataFrame(filled_X,
                               columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head()

In [ ]:
car_sales_filled.isna().sum()

In [ ]:
# Let's try and convert our data to numbers
# turn categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

In [ ]:
# we have got our data as nums and filled (no missing values)
# lets fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

In [ ]:
len(car_sales_filled), len(car_sales)

In [ ]:
what_were_covering

## 2. choosing the right estimator/algorithm for our problem


some things to note:

* sklearn refers to machine learning models, algorithms as estimators
* classification problem = predicting a category (dead or not)
    * sometimes we will see 'clf' (classifier) used as a classificaton estimator
* regression problem = predicting a number (selling price of a car)

If Im working on a ML problem and looking to use sklearn and not sure what model I shoul ise, refer to the sklearn Ml map: https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

### 2.1 picking a ML model for a regression problem

Lets use the california housing data set = https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing

In [37]:
# get california housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [52]:
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [53]:
housing_df["target"]=housing["target"]
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [54]:
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [55]:
# import algorithm/estimator
from sklearn.linear_model import Ridge


# setup random seed
np.random.seed(42)

# create the data
X = housing_df.drop("target", axis=1)
y = housing_df["target"] # median house price in $100, 000s

#split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate and fit the model (on the training set)
model = Ridge()
model.fit(X_train, y_train)

# check the score of the model (on the test set)
model.score(X_test, y_test)

0.5758549611440125

sad accuracy score, i try another model (Ridge dint fit or score didnt fit our needs)

try ensemble (combo of smaller models to make better predictions than just a single model)

sklearns ensemble models can be found here: https://scikit-learn.org/stable/modules/ensemble.html

In [61]:
# import the randomforestregressor model class from the ensemble module
from sklearn.ensemble import RandomForestRegressor

# setup  random seed
np.random.seed(42)

# create the data
X = housing_df.drop("target", axis=1)
y= housing_df["target"]

# split it inot test and train sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# create random forest model
model = RandomForestRegressor()
model.fit(X_train, y_train)

# check the score of the model (on the test set)
model.score(X_test, y_test)

0.8066196804802649

In [62]:
# yeeee

## 2.2 picking a model for a classification problem

lets go to map... https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [68]:
heart_disease=pd.read_csv("csv/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [69]:
len(heart_disease)

303

consulting the map and its says to try `LinearSVC`

In [72]:
# import the linearscv estimator class
from sklearn.svm import LinearSVC

# setup random seed
np.random.seed(42)

# make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate linearscv
clf=LinearSVC(max_iter=1000)
clf.fit(X_train, y_train)

# evaluate the linearsvc
clf.score(X_test,y_test)

/Users/viragvegh/Desktop/sample_project/env/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8688524590163934

In [73]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [75]:
# import the randomforestclassifier estimator class
from sklearn.ensemble import RandomForestClassifier

# setup random seed
np.random.seed(42)

# make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate randomforestclassifier
clf= RandomForestClassifier()
clf.fit(X_train, y_train)

# evaluate the randomforestclassifier
clf.score(X_test,y_test)

0.8524590163934426

tidbit:
  1. if you have structured data use ensemble models such as randomforest
  2. unstructured data: deeplearning, transferlearning

In [76]:
what_were_covering

['0. an end-to-end sklearn workflow',
 '1. getting data ready',
 '2. choose right estimator/algorithm for our problems',
 '3. fit the model/algorithm and use it to make predictions on our data',
 '4. evaluating a model',
 '5. improve a model',
 '6. save and load trained model',
 '7. putting it all together']

## 3. fit the model/algorithm and use it to make predictions on our data

### 3.1 fitting the model to the data

* `X` = feature variables, data
* `y` = lables, targets, target variables

In [82]:
# import the randomforestclassifier estimator class
from sklearn.ensemble import RandomForestClassifier

# setup random seed
np.random.seed(42)

# make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate randomforestclassifier
clf= RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

# fit the modle to the data (training the machine learning model)
clf.fit(X_train, y_train)

# evaluate the randomforestclassifier (use the patterns the model has learned)
clf.score(X_test,y_test)

0.8688524590163934

In [79]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [80]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [81]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

### 3.2 make predictions useing a machine learning model
2 ways to make predictions:
 1. `predict()`
 2. `predict_proba()`

In [83]:
# use a trained model to make predictions
clf.predict(np.array([1,2,3,4,5,6])) # this doesnt work

/Users/viragvegh/Desktop/sample_project/env/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4. 5. 6.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [84]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
249   69    1   2       140   254    0        0      146      0      2.0   
104   50    1   2       129   196    0        1      163      0      0.0   
300   68    1   0       144   193    1        1      141      0      3.4   
193   60    1   0       145   282    0        0      142      1      2.8   
184   50    1   0       150   243    0        0      128      0      2.6   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2  
..     ...  ..   ...  
249      1   3     3  
104      2   0     2  
300      1   2     3  
193      1   2     3  
184      1   0     3  

[61 rows x 13 columns]

In [85]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [87]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [88]:
# compare preds to truth labels to evaluate the model
y_preds=clf.predict(X_test)
np.mean(y_preds == y_test)

0.8688524590163934

In [89]:
clf.score(X_test, y_test)

0.8688524590163934

In [90]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8688524590163934

make preds with `predict_proba()`

In [92]:
# predict_proba() returns probabilties of a classification label
clf.predict_proba(X_test[:5])

array([[0.87, 0.13],
       [0.4 , 0.6 ],
       [0.4 , 0.6 ],
       [0.92, 0.08],
       [0.21, 0.79]])

In [93]:
# lets predict on the same data...
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [100]:
X_test[:5]

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20046  1.6812      25.0  4.192201   1.022284      1392.0  3.877437     36.06   
3024   2.5313      30.0  5.039384   1.193493      1565.0  2.679795     35.14   
15663  3.4801      52.0  3.977155   1.185877      1310.0  1.360332     37.80   
20484  5.7376      17.0  6.163636   1.020202      1705.0  3.444444     34.28   
9814   3.7250      34.0  5.492991   1.028037      1063.0  2.483645     36.62   

       Longitude  
20046    -119.01  
3024     -119.46  
15663    -122.44  
20484    -118.72  
9814     -121.93

In [101]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

`predict()` can also be used for regression models

In [102]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [106]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# create the data
X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# create model instance
model = RandomForestRegressor(n_estimators=100)

# fit the model
model.fit(X_train, y_train)

# make preds
y_preds = model.predict(X_test)

In [107]:
y_preds[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54029  , 2.33176  , 1.6549701,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [108]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [111]:
len(y_test)

4128

In [109]:
len(y_preds)

4128

In [110]:
# compare preds to truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

0.3265721842781009

In [112]:
housing_df["target"]

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target, Length: 20640, dtype: float64

In [113]:
what_were_covering

['0. an end-to-end sklearn workflow',
 '1. getting data ready',
 '2. choose right estimator/algorithm for our problems',
 '3. fit the model/algorithm and use it to make predictions on our data',
 '4. evaluating a model',
 '5. improve a model',
 '6. save and load trained model',
 '7. putting it all together']

## 4. evalutaing ml model

3 ways to evaluate scikit learn models/estimators:
   1. estimators built in `score()` method
   2. the `scoring` parameter
   3. problem-specific metric functions


read more: https://scikit-learn.org/stable/modules/model_evaluation.html

### 4.1 eavluating with the `score()` method

In [120]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

# create X & y
X = heart_disease.drop(["target"], axis=1)
y= heart_disease["target"]

# create train/test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate randomforestclassifier
clf = RandomForestClassifier(n_estimators=10)

# fit model (training the machine learning model)
clf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [121]:
# the highest value for the .score() method is 1.0, the lowest is 0.0
clf.score(X_train, y_train)

1.0

In [116]:
y_train

132    1
202    0
196    0
75     1
176    0
      ..
188    0
71     1
106    1
270    0
102    1
Name: target, Length: 242, dtype: int64

In [117]:
clf.score(X_test, y_test)

0.8524590163934426

lets use `score()` on our regression problem

In [136]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = housing_df.drop(["target"], axis=1)
y = housing_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor(n_estimators=80)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=80)

In [137]:
# the default score() evaluation metrics is r_squared for regression algorithms
# highest = 1.0 lowst = 0.0
model.score(X_test, y_test)

0.8063285573441384

In [138]:
model.score(X_test, y_test)

0.8063285573441384

In [139]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [140]:
y_test.mean()

2.0550030959302275

### 4.2 evaluating the model using the `scoring` paramaeter

In [142]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

# create X & y
X = heart_disease.drop(["target"], axis=1)
y= heart_disease["target"]

# create train/test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate randomforestclassifier
clf = RandomForestClassifier(n_estimators=10)

# fit model (training the machine learning model)
clf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [143]:
clf.score(X_test, y_test)

0.8524590163934426

In [145]:
cross_val_score(clf, X, y, cv=5)

array([0.7704918 , 0.8852459 , 0.75409836, 0.85      , 0.78333333])

In [146]:
cross_val_score(clf, X, y, cv=50)

array([0.71428571, 1.        , 0.71428571, 1.        , 0.83333333,
       0.83333333, 1.        , 0.66666667, 0.66666667, 0.83333333,
       0.66666667, 1.        , 1.        , 0.66666667, 0.5       ,
       0.83333333, 1.        , 1.        , 0.83333333, 0.83333333,
       1.        , 0.83333333, 0.83333333, 0.66666667, 1.        ,
       0.5       , 0.83333333, 0.66666667, 0.5       , 1.        ,
       0.66666667, 0.83333333, 0.5       , 0.83333333, 0.83333333,
       0.83333333, 1.        , 1.        , 0.83333333, 0.66666667,
       0.83333333, 0.33333333, 0.5       , 0.5       , 0.66666667,
       0.66666667, 0.83333333, 0.66666667, 0.83333333, 0.83333333])

In [149]:
np.random.seed(42)

# single training and test split score
clf_single_score= clf.score(X_test, y_test)

# take mean of 5-fold cv score
clf_cross_val_score = np.mean(cross_val_score(clf, X, y, cv=5))

# compare the two
clf_single_score, clf_cross_val_score

(0.8524590163934426, 0.8150819672131148)

In [150]:
# default scoring parameter of classifier = mean accuracy
clf.score()

TypeError: score() missing 2 required positional arguments: 'X' and 'y'

In [151]:
# scoing parameter set to None by default
cross_val_score(clf, X, y, cv=5, scoring=None)

array([0.80327869, 0.81967213, 0.85245902, 0.76666667, 0.75      ])

### 4.2.1 classification model evaluation metrics

1. accuracy
2. area under ROC curve
3. confusion matrix
4. classification report

### Accuracy

In [159]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [153]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y=heart_disease["target"]

clf=RandomForestClassifier(n_estimators=100)
cross_val_score = cross_val_score(clf, X, y, cv=5)

In [154]:
np.mean(cross_val_score)

0.8248087431693989

In [158]:
print(f"Heart Disease Classifier Cross-Validated Accuracy: {np.mean(cross_val_score) * 100: .2f}%")

Heart Disease Classifier Cross-Validated Accuracy:  82.48%


**area under the receiver operating characteristic curve (AUC/ROC)** 

* area under curve (AUC)
* ROC curve

ROC curves are a composition of models true positive rate (tpr) versus a model false positive rate (fpr)

* true positive = model predicts 1 when truth is 1
* false positive = model predicts 1 when truth is 0
* true negative = model predicts 0 when truth is 0
* false negative = model predicts 0 when truth is 1